name: Release build
# Original source: https://github.com/Bookshelf-Writer/scripts-for-integration/blob/main/workflows/Example-Build.yml
# When integrating, actions must have write permissions

on:
  release:
    branches:
      - 'main'
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build ${{ github.ref }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      ########################################################################################################################

      - name: Load Info from Build
        run: |
          nameBuild=$(./_run/scripts/sys.sh -n)
          versionBuild=$(./_run/scripts/sys.sh -v)

          echo "BUILD_NAME=$nameBuild" >> $GITHUB_ENV
          echo "BUILD_VER=$versionBuild" >> $GITHUB_ENV
          
          echo "NAME: $nameBuild"
          echo "VER: $versionBuild"

      - name: Check Tag
        run: |
          if [[ "${{ github.event.release.tag_name }}" != "${{ env.BUILD_VER }}" ]]; then
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}"
          
            echo "::error ::Incorrect release tag. Should match the [${{ env.BUILD_VER }}]."
            exit 1
          fi

      - name: Checkout to the [main]
        run: |
          if git branch -a | grep -qw "origin/main"; then
            git checkout main
          else
            echo "No known branch found!"
            exit 1
          fi

      - name: Push new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          new_version=$(./_run/scripts/sys.sh --increment --minor)
          
          git add ./_run/values/ver.txt
          
          git commit -m "actions [$new_version] "$'\n'"Build: [${{ env.BUILD_VER }}] >> [$new_version]"
          git push origin HEAD:main
